server:
  port: 8080
  servlet:
    context-path: /screening

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/creen_test"
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  signerKey: "95XbhucZmceg0wCS3hITBSP2DVyDds1f1W9H4LCckAPMm/UqNImSvxoaq8qmzY83"